// <auto-generated />
using System;
using LauraModasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LauraModasAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LauraModasAPI.Models.BuyLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("DateOfPayment")
                        .HasColumnType("date");

                    b.Property<string>("NameOfProduct")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<double>("PaymentValue")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("BuyLogs");
                });

            modelBuilder.Entity("LauraModasAPI.Models.BuyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerModelId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfPayment")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(350)");

                    b.Property<double>("InstallmentValue")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("int");

                    b.Property<double>("RemainingValue")
                        .HasColumnType("double");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CustomerModelId");

                    b.ToTable("Buys");
                });

            modelBuilder.Entity("LauraModasAPI.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SecondPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LauraModasAPI.Models.InstallmentModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DateOfPayment")
                        .HasColumnType("date");

                    b.Property<double>("InstallmentValue")
                        .HasColumnType("double");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("int");

                    b.Property<double>("RemainingValue")
                        .HasColumnType("double");

                    b.Property<double>("TotalValue")
                        .HasColumnType("double");

                    b.HasKey("CustomerId");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("LauraModasAPI.Models.LotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AmountValue")
                        .HasColumnType("double");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("LauraModasAPI.Models.BuyModel", b =>
                {
                    b.HasOne("LauraModasAPI.Models.CustomerModel", "CustomerModel")
                        .WithMany("BuysModel")
                        .HasForeignKey("CustomerModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerModel");
                });

            modelBuilder.Entity("LauraModasAPI.Models.InstallmentModel", b =>
                {
                    b.HasOne("LauraModasAPI.Models.CustomerModel", "Customer")
                        .WithOne("Installment")
                        .HasForeignKey("LauraModasAPI.Models.InstallmentModel", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LauraModasAPI.Models.CustomerModel", b =>
                {
                    b.Navigation("BuysModel");

                    b.Navigation("Installment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
